AhorraYa.Client/Controllers/BrandsController.cs
using AhorraYa.WebClient.ViewModels.Brand;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace AhorraYa.WebClient.Controllers
{
    public class BrandsController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7284/");
        private readonly HttpClient _httpClient;
        private readonly IMapper _mapper;
        private readonly string _jwtToken;

        public BrandsController(IMapper mapper)
        {
            _mapper = mapper;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
            _jwtToken = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImE0NmM1ZmY3LTJkNDktNDNiMS0wZDM1LTA4ZGUyMjJkMzI2MyIsInN1YiI6ImE0NmM1ZmY3LTJkNDktNDNiMS0wZDM1LTA4ZGUyMjJkMzI2MyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzY0MzQ4NDYxLCJleHAiOjE3NjQzNjI4NjEsImlhdCI6MTc2NDM0ODQ2MX0.NpS6OqAzL43YdmJNTsX5sbxN604D7Q5maKZBKkN2AhoEN7xyk7uqBOB9EOs4Kj_bLtbldjC14PHJz3xk6jIfsA";
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? searchText, string? orderBrands)
        {
            List<BrandListVm> list = new List<BrandListVm>();
            //Paso el token de autorización.
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
            //Envió una petición al endpoint y guardo la rta completa del servidor
            HttpResponseMessage response = await _httpClient.GetAsync($"api/Brands/All");

            if(response.IsSuccessStatusCode)//(200 y 299)
            {
                string data = await response.Content.ReadAsStringAsync();
                list = JsonConvert.DeserializeObject<List<BrandListVm>>(data);
            }

            ViewBag.CurrentSearchText = searchText;
            ViewBag.OrderBrands = orderBrands;

            return View(list);
        }
    }
}

AhorraYa.Client/Controllers/CategoriesController.cs
using AhorraYa.Application.Dtos.Category;
using AhorraYa.WebClient.ViewModels.Category;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace AhorraYa.WebClient.Controllers
{
    public class CategoriesController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7284/");
        private readonly HttpClient _httpClient;
        private readonly IMapper _mapper;
        private readonly string _jwtToken;

        public CategoriesController(IMapper mapper)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
            _mapper = mapper;
            _jwtToken = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImE0NmM1ZmY3LTJkNDktNDNiMS0wZDM1LTA4ZGUyMjJkMzI2MyIsInN1YiI6ImE0NmM1ZmY3LTJkNDktNDNiMS0wZDM1LTA4ZGUyMjJkMzI2MyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzY0MzQ4NDYxLCJleHAiOjE3NjQzNjI4NjEsImlhdCI6MTc2NDM0ODQ2MX0.NpS6OqAzL43YdmJNTsX5sbxN604D7Q5maKZBKkN2AhoEN7xyk7uqBOB9EOs4Kj_bLtbldjC14PHJz3xk6jIfsA";
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? searchText, string? orderCategories)
        {
            List<CategoryListVm> list = new List<CategoryListVm>();

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
            HttpResponseMessage response = await _httpClient.GetAsync($"api/Categories/All?searchText={searchText}&orderBy={orderCategories}");

            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                list = JsonConvert.DeserializeObject<List<CategoryListVm>>(data);
            }

            ViewBag.CurrentSearchText = searchText;
            ViewBag.OrderCategories = orderCategories;

            return View(list);
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            if (id is null || id == 0)
            {
                var model = new CategoryEditVm()
                {
                    Id = 0
                };
                return View(model);
            }
            try
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
                int idToFetch = id.Value;
                HttpResponseMessage response = await _httpClient.GetAsync($"api/Categories/GetById?id={idToFetch}");
                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    CategoryRequestDto? categoryDto = JsonConvert.DeserializeObject<CategoryRequestDto>(data);

                    if (categoryDto is null)
                    {
                        return NotFound($"Category With Id {id} Not Found!!");
                    }

                    CategoryEditVm categoryVm = _mapper.Map<CategoryEditVm>(categoryDto);
                    return View(categoryVm);
                }

                return NotFound($"Category With Id {id} Not Found. API status: {response.StatusCode}");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CategoryEditVm categoryVm)
        {
            if (ModelState.IsValid)
            {
                CategoryRequestDto categoryRequest = _mapper.Map<CategoryRequestDto>(categoryVm);
                try
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
                    string jsonContent = JsonConvert.SerializeObject(categoryRequest);
                    var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                    HttpResponseMessage response;
                    string succesMessage;
                    if (categoryRequest.Id == 0)
                    {
                        response = await _httpClient.PostAsync("api/Categories/Create", content);
                        succesMessage = "successfully created category";
                    }
                    else
                    {
                        string url = $"api/Categories/Update?id={categoryRequest.Id}";
                        response = await _httpClient.PutAsync(url, content);
                        succesMessage = "successfully update category";
                    }

                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = succesMessage;
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        string errorData = await response.Content.ReadAsStringAsync();

                        ModelState.AddModelError("", $"Error {response.StatusCode}");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Error {ex.Message}");
                }
            }
            return View(categoryVm);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }
            try
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
                int idToFetch = id.Value;
                HttpResponseMessage response;

                response = await _httpClient.GetAsync($"api/Categories/GetById?id={idToFetch}");
                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    CategoryRequestDto? categoryDto = JsonConvert.DeserializeObject<CategoryRequestDto>(data);

                    if (categoryDto is null)
                    {
                        return NotFound($"Category With Id {id} Not Found!!");
                    }

                    CategoryEditVm categoryVm = _mapper.Map<CategoryEditVm>(categoryDto);
                    return View(categoryVm);
                }
                else
                {
                    return NotFound($"Category With Id {id} Not Found. API status: {response.StatusCode}");
                }
            }
            catch (Exception)
            {
                TempData["error"] = "Error while trying to get a category";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }
            try
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _jwtToken);
                int idToDelete = id.Value;


                HttpResponseMessage response = await _httpClient.DeleteAsync($"api/Categories/Remove?id={idToDelete}");
                if (response.IsSuccessStatusCode)
                {
                    TempData["success"] = "Category deleted correctly";
                    return RedirectToAction("Index");
                }
                else
                {
                    string errorData = await response.Content.ReadAsStringAsync();
                    TempData["error"] = errorData;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                TempData["error"] = ex.Message;
                return RedirectToAction("Index");
            }

        }
    }
}

AhorraYa.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AhorraYa.Client</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AhorraYa.Client.styles.css" asp-append-version="true" />

</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>AhorraYa</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">Product</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Brands" asp-action="Index">Brand</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Localities" asp-action="Index">Localities</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Shops" asp-action="Index">Shop</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a></li>


                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="container flex-grow-1 pb-3 pb-5">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            &copy; 2025 - AhorraYa.Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>